# Generated by Django 5.2.10 on 2026-05-01 15:09

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('nombre_razon_social', models.CharField(max_length=100, verbose_name='Nombre / Razón Social')),
                ('documento', models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{7,11}$', 'Documento: 7 a 11 dígitos')], verbose_name='Documento (DNI/CUIT)')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='Email')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'indexes': [models.Index(fields=['nombre_razon_social'], name='idx_cliente_nombre')],
            },
        ),
    ]
