# Generated by Django 5.2.10 on 2026-05-01 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturas', '0001_initial'),
        ('ordenes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='orden',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='factura', to='ordenes.ordentrabajo', verbose_name='Orden de Trabajo'),
        ),
        migrations.AddField(
            model_name='pago',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pagos', to='facturas.factura', verbose_name='Factura'),
        ),
        migrations.AddField(
            model_name='pago',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['cliente'], name='idx_factura_cliente'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['estado_pago'], name='idx_factura_estado'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['factura'], name='idx_pago_factura'),
        ),
    ]
