# Generated by Django 5.2.10 on 2026-05-01 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('ordenes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientostock',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to='ordenes.ordentrabajo', verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='productobase',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='productos', to='inventario.categoriaproducto', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.productobase', verbose_name='Producto'),
        ),
        migrations.CreateModel(
            name='Neumatico',
            fields=[
                ('productobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario.productobase')),
                ('ancho', models.IntegerField(verbose_name='Ancho (mm)')),
                ('perfil', models.IntegerField(verbose_name='Perfil')),
                ('diametro_rin', models.IntegerField(verbose_name='Diámetro Rin')),
                ('indice_carga', models.CharField(blank=True, max_length=5, null=True, verbose_name='Índice de Carga')),
                ('indice_velocidad', models.CharField(blank=True, max_length=5, null=True, verbose_name='Índice de Velocidad')),
                ('tipo_neumatico', models.CharField(blank=True, choices=[('VERANO', 'Verano'), ('INVIERNO', 'Invierno'), ('ALL_SEASON', 'All Season')], max_length=20, null=True, verbose_name='Tipo')),
                ('marca_neumatico', models.CharField(max_length=30, verbose_name='Marca')),
                ('modelo_neumatico', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Neumático',
                'verbose_name_plural': 'Neumáticos',
                'db_table': 'neumatico',
                'indexes': [models.Index(fields=['ancho', 'perfil', 'diametro_rin'], name='idx_neumatico_medida')],
            },
            bases=('inventario.productobase',),
        ),
        migrations.CreateModel(
            name='RepuestoGenerico',
            fields=[
                ('productobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario.productobase')),
                ('marca_repuesto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca Repuesto')),
                ('modelo_repuesto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo Repuesto')),
                ('compatibilidad_vehicular', models.TextField(blank=True, null=True, verbose_name='Compatibilidad Vehicular')),
                ('numero_parte', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° de Parte')),
            ],
            options={
                'verbose_name': 'Repuesto',
                'verbose_name_plural': 'Repuestos',
                'db_table': 'repuesto_generico',
                'indexes': [models.Index(fields=['marca_repuesto'], name='idx_repuesto_marca')],
            },
            bases=('inventario.productobase',),
        ),
        migrations.AddIndex(
            model_name='productobase',
            index=models.Index(fields=['codigo_sku'], name='idx_producto_sku'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['producto'], name='idx_movimiento_producto'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['fecha_creacion'], name='idx_movimiento_fecha'),
        ),
    ]
