# Generated by Django 5.2.10 on 2026-05-01 15:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('patente', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Patente')),
                ('marca', models.CharField(max_length=30, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('anio', models.IntegerField(blank=True, null=True, verbose_name='Año')),
                ('vin', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='VIN / Chasis')),
                ('kilometraje_actual', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Kilometraje Actual')),
                ('color', models.CharField(blank=True, max_length=30, null=True, verbose_name='Color')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='vehiculos', to='clientes.cliente', verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehiculo',
                'indexes': [models.Index(fields=['cliente'], name='idx_vehiculo_cliente')],
            },
        ),
    ]
