# Generated by Django 5.2.10 on 2026-05-01 15:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('precio_base', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio Base')),
            ],
            options={
                'verbose_name': 'Tipo de Servicio',
                'verbose_name_plural': 'Tipos de Servicios',
                'db_table': 'tipo_servicio',
            },
        ),
        migrations.CreateModel(
            name='IntervaloMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('intervalo_kilometros', models.IntegerField(blank=True, null=True, verbose_name='Intervalo (km)')),
                ('intervalo_meses', models.IntegerField(blank=True, null=True, verbose_name='Intervalo (meses)')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervalos', to='mantenimiento.tiposervicio', verbose_name='Tipo de Servicio')),
            ],
            options={
                'verbose_name': 'Intervalo de Mantenimiento',
                'verbose_name_plural': 'Intervalos de Mantenimiento',
                'db_table': 'intervalo_mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='AlertaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('kilometraje_estimado', models.IntegerField(blank=True, null=True, verbose_name='Kilometraje Estimado')),
                ('fecha_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha Estimada')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('NOTIFICADA', 'Notificada'), ('COMPLETADA', 'Completada'), ('IGNORADA', 'Ignorada')], db_index=True, default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_notificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Notificación')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='vehiculos.vehiculo', verbose_name='Vehículo')),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='alertas', to='mantenimiento.tiposervicio', verbose_name='Tipo de Servicio')),
            ],
            options={
                'verbose_name': 'Alerta de Mantenimiento',
                'verbose_name_plural': 'Alertas de Mantenimiento',
                'db_table': 'alerta_mantenimiento',
                'indexes': [models.Index(fields=['vehiculo'], name='idx_alerta_vehiculo'), models.Index(fields=['estado'], name='idx_alerta_estado')],
            },
        ),
    ]
